<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Gitclient</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath></BaseOutputPath>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="model\ChangeType.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="libgit2.so" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="libgit2.so">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CMake" Version="3.5.2">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="LibGit2Sharp" Version="0.30.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="git2.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
  </ItemGroup>

</Project>
